### ISSUE TITLE
py version?

### ISSUE THREAD

**Issue by Minhe173** [DismissedGuy/honeygain-ovpn#1]
@DismissedGuy

**Comment by DismissedGuy** [comment]
I'm going to make a wild guess and assume you want to know what python version the manager runs on?

Not sure what the lower bound is, but probably 3.6 and higher since it uses f-strings. In any case, please do not worry about that and just run it as a Docker container instead.

**Comment by Minhe173** [comment]
how to install docker

**Comment by DismissedGuy** [comment]
I'm going to assume you figured it out... if not, feel free to reopen.
