### ISSUE TITLE
help:(

### ISSUE THREAD

**Issue by ProxiedMail** [DismissedGuy/honeygain-ovpn#3]
![image](https://user-images.githubusercontent.com/128895488/227709167-75ff24c7-88cb-4973-9be4-ffd0559d59a2.png)

**Comment by ProxiedMail** [comment]
![image](https://user-images.githubusercontent.com/128895488/227709229-e3787cd5-ed7c-4038-9c0b-946a1ce1758f.png)

**Comment by ProxiedMail** [comment]
@DismissedGuy

**Comment by DismissedGuy** [comment]
Is your Docker running? Also, try Docker desktop instead

**Comment by ProxiedMail** [comment]
![image](https://user-images.githubusercontent.com/128895488/227721223-20348aea-ca38-47ae-9ff5-15c5aecd1f6e.png)
![image](https://user-images.githubusercontent.com/128895488/227721237-a1822d63-291b-475e-a734-1ac3323fcbe4.png)
![image](https://user-images.githubusercontent.com/128895488/227721265-be387bb5-31d1-47fe-8a3c-724573eb3ef7.png)
idk wdym root here @DismissedGuy

**Comment by ProxiedMail** [comment]
tried diff root(s), none worked:((

**Comment by ProxiedMail** [comment]
@DismissedGuy

**Comment by DismissedGuy** [comment]
You need to rename the .env.example file to .env and then run it using docker compose. I don't use Windows so I'm not exactly sure how Docker Desktop works, but if you don't do that it won't pass the env vars properly.

The root is simply the directory in which the manager is located.

Also, please do not mention me every time, I get a notification from every message you send, mentioning me won't make me respond faster.

**Comment by ProxiedMail** [comment]
AH STILL EXITED

**Comment by ProxiedMail** [comment]
![image](https://user-images.githubusercontent.com/128895488/227722489-e2f72e71-01d0-4bb0-929f-e7bf4096e7e7.png)
![image](https://user-images.githubusercontent.com/128895488/227722490-b8eca5ad-8735-4263-9639-78f0cb3574ec.png)

**Comment by DismissedGuy** [comment]
try removing the existing containers and try again.

**Comment by ProxiedMail** [comment]
![image](https://user-images.githubusercontent.com/128895488/227722530-e0549200-0b09-469f-ba52-9127b4618726.png)

**Comment by ProxiedMail** [comment]
> try removing the existing containers and try again.

wdym?

**Comment by DismissedGuy** [comment]
> ![image](https://user-images.githubusercontent.com/128895488/227722530-e0549200-0b09-469f-ba52-9127b4618726.png)
> 

Did you specify those variables in your env file?

**Comment by ProxiedMail** [comment]
yes

**Comment by DismissedGuy** [comment]
> > try removing the existing containers and try again.
> 
> wdym?

Remove the old docker containers and then run the manager again

**Comment by ProxiedMail** [comment]
rerun?

**Comment by DismissedGuy** [comment]
After removing the old containers, yes

**Comment by ProxiedMail** [comment]
![image](https://user-images.githubusercontent.com/128895488/227722695-5d2ef067-8159-4b20-b2db-2bcd6ead4666.png)

**Comment by ProxiedMail** [comment]
:bruh:

**Comment by ProxiedMail** [comment]
![Uploading image.png…]()
delete?

**Comment by ProxiedMail** [comment]
![image](https://user-images.githubusercontent.com/128895488/227722762-beb158ed-5a28-47cb-b581-a33622a9d735.png)

**Comment by ProxiedMail** [comment]
dismissedguyy

**Comment by ProxiedMail** [comment]
ahh another error after deletin'
honeygain_manager  | INFO:root:Starting client au
honeygain_manager  | Traceback (most recent call last):
honeygain_manager  |   File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
honeygain_manager  |     response.raise_for_status()
honeygain_manager  |   File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
honeygain_manager  |     raise HTTPError(http_error_msg, response=self)
honeygain_manager  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/containers/create?name=honeygain-au
honeygain_manager  | 
honeygain_manager  | During handling of the above exception, another exception occurred:
honeygain_manager  | 
honeygain_manager  | Traceback (most recent call last):
honeygain_manager  |   File "/app/manager.py", line 159, in <module>
honeygain_manager  |     sys.exit(main())
honeygain_manager  |   File "/app/manager.py", line 151, in main
honeygain_manager  |     run_once()
honeygain_manager  |   File "/app/manager.py", line 140, in run_once
honeygain_manager  |     _start_client(device)
honeygain_manager  |   File "/app/manager.py", line 98, in _start_client
honeygain_manager  |     docker_client.containers.run(
honeygain_manager  |   File "/usr/lib/python3.10/site-packages/docker/models/containers.py", line 819, in run
honeygain_manager  |     container = self.create(image=image, command=command,
honeygain_manager  |   File "/usr/lib/python3.10/site-packages/docker/models/containers.py", line 878, in create
honeygain_manager  |     resp = self.client.api.create_container(**create_kwargs)
honeygain_manager  |   File "/usr/lib/python3.10/site-packages/docker/api/container.py", line 428, in create_container
honeygain_manager  |     return self.create_container_from_config(config, name)
honeygain_manager  |   File "/usr/lib/python3.10/site-packages/docker/api/container.py", line 439, in create_container_from_config
honeygain_manager  |     return self._result(res, True)
honeygain_manager  |   File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
honeygain_manager  |     self._raise_for_status(response)
honeygain_manager  |   File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
honeygain_manager  |     raise create_api_error_from_http_exception(e)
honeygain_manager  |   File "/usr/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
honeygain_manager  |     raise cls(e, response=response, explanation=explanation)
honeygain_manager  | docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/containers/create?name=honeygain-au: Internal Server Error ("b'mount denied:\nthe source path "\\\\Users\\\\admin\\\\Downloads\\\\honeygain-ovpn-main\\\\honeygain-ovpn-main/configs/config-au.ovpn/config.ovpn"\ndoesn\'t contains colon'")
honeygain_manager exited with code 1

**Comment by ProxiedMail** [comment]
@DismissedGuy :( reply

**Comment by ProxiedMail** [comment]
doesn't contains colon???

**Comment by DismissedGuy** [comment]
Please stop spamming this issue, I have other things to do so I can't just reply immediately when you need help. You should be glad I'm even helping you at all considering this was never meant as a user-friendly project.

What I find strange is that you're seemingly getting a manager error in the client container and that both the manager and client containers have the same size. I'm guessing you built and tagged the wrong image, so remove all images and containers and re-run the docker build command in the client directory, then try again.

As for the missing colon, I'm not sure what you messed up there. There is clearly a colon specified in the manager so maybe you accidentally removed it. Redownload the repo to make sure.

**Comment by ProxiedMail** [comment]
alr thx

**Comment by ProxiedMail** [comment]
Redownloaded the repo but still same error

**Comment by ProxiedMail** [comment]
idk whats the root

**Comment by ProxiedMail** [comment]
C:\Users\admin\Downloads\honeygain-ovpn-main\honeygain-ovpn-main
C:\Users\admin\Downloads\honeygain-ovpn-main\honeygain-ovpn-main\manager
C:\Users\admin\Downloads\honeygain-ovpn-main\honeygain-ovpn-main\configs
tried ^^ but none worked

**Comment by DismissedGuy** [comment]
Are you sure it's in `Downloads\honeygain-ovpn-main\honeygain-ovpn-main` and not `Downloads\honeygain-ovpn-main\`?

Also, in one of your first screenshots you got it to recognize the configs right?

**Comment by ProxiedMail** [comment]
ye

**Comment by DismissedGuy** [comment]
ROOT is only used for the manager to know how to mount the specified config in each client container. So if you're still getting those missing EMAIL / PASS issues then that's not the cause of the problem.

You can try running it on a Linux box; maybe (but I doubt it) the syntax is different on Windows, or it somehow doesn't play nicely with the whole Docker Desktop thing - the manager integrates quite tightly with Docker itself. If that doesn't work either then I don't know what else to try, sorry.
